In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('../data/raw/Teen_Mental_Health_Dataset.csv')

In [14]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [15]:
df['usage_intensity'] = df['daily_social_media_hours'] / df['sleep_hours']
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184

In [16]:
df['stress_per_hour'] = df['stress_level'] / df['daily_social_media_hours']
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568,0.253165
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500,4.210526
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053,1.538462
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464,0.135135
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184,0.638298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,1.030303,0.441176
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0,0.287500,3.043478
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0,0.195402,0.588235
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0,0.458824,1.794872
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,0.723077,1.063830

In [17]:
df['anxiety_sleep_ratio'] = df['anxiety_level'] / df['sleep_hours']

In [18]:
df['usage_category'] = pd.cut(
    df['daily_social_media_hours'],
    bins=[0,2,5,10],
    labels=['Low','Medium','High']
)

df['sleep_category'] = pd.cut(
    df['sleep_hours'],
    bins=[0,5,7,10],
    labels=['Poor','Average','Good']
)

In [19]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour,anxiety_sleep_ratio,usage_category,sleep_category
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568,0.253165,0.270270,High,Good
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500,4.210526,0.125000,Low,Good
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053,1.538462,0.526316,Low,Good
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464,0.135135,1.014493,High,Average
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184,0.638298,1.020408,Medium,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,1.030303,0.441176,0.606061,High,Average
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0,0.287500,3.043478,0.500000,Medium,Good
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0,0.195402,0.588235,0.114943,Low,Good
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0,0.458824,1.794872,1.058824,Medium,Good
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,0.723077,1.063830,1.076923,Medium,Average

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  usage_intensity           1200 non-null   float64
 14  stress_per_hour           1200 non-null   float64
 15  anxiety_sleep_ratio       1200 non-null   float64
 16  usage_category            1200 non-null   category
 17  sleep_category            1200 non-null   category
dtypes: category(2), float64(8), int64(5), str(3)
memory usage: 171.2 KB

In [21]:
df.sample(15)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour,anxiety_sleep_ratio,usage_category,sleep_category
1045,17,female,7.3,Instagram,6.7,1.0,3.41,1.7,medium,6,5,2,0,1.089552,0.821918,0.746269,High,Average
1014,18,male,5.3,Both,8.2,1.9,3.87,1.9,low,2,9,8,0,0.646341,0.377358,1.097561,High,Good
384,13,male,7.5,TikTok,4.8,0.7,2.91,2.0,high,10,9,1,1,1.562500,1.333333,1.875000,High,Poor
317,19,female,1.4,Instagram,6.6,1.8,3.07,0.0,low,5,2,6,0,0.212121,3.571429,0.303030,Low,Average
849,19,male,5.4,Instagram,4.9,0.6,3.17,0.0,low,5,6,10,0,1.102041,0.925926,1.224490,High,Poor
850,15,female,2.7,TikTok,7.6,2.5,2.37,1.9,high,1,8,7,0,0.355263,0.370370,1.052632,Medium,Good
749,19,female,6.0,Both,6.3,2.8,3.98,2.0,medium,2,6,2,0,0.952381,0.333333,0.952381,High,Average
951,17,female,3.5,Both,8.5,2.2,2.11,1.3,medium,8,8,2,0,0.411765,2.285714,0.941176,Medium,Good
759,18,male,3.6,Instagram,4.7,2.5,2.73,1.2,medium,9,7,6,0,0.765957,2.500000,1.489362,Medium,Poor
543,17,female,5.1,TikTok,8.6,1.9,3.33,1.1,low,1,7,8,0,0.593023,0.196078,0.813953,High,Good
937,15,female,4.6,TikTok,5.3,3.0,3.25,0.2,low,1,8,7,0,0.867925,0.217391,1.509434,Medium,Average
891,16,male,4.8,Both,5.4,0.9,2.06,1.9,low,8,3,2,0,0.888889,1.666667,0.555556,Medium,Average
426,14,male,6.1,Both,7.6,1.4,2.72,0.9,low,9,3,3,0,0.802632,1.475410,0.394737,High,Good
1108,13,female,3.5,Instagram,6.9,1.6,2.08,0.7,low,9,9,9,0,0.507246,2.571429,1.304348,Medium,Average
603,16,male,6.9,Instagram,6.8,1.1,3.33,1.0,medium,7,9,4,0,1.014706,1.014493,1.323529,High,Average

In [22]:
df.to_csv('../data/processed/process_Teen_mental_health.csv', index=False)