In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/Teen_Mental_Health_Dataset.csv')

In [3]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [4]:
df['usage_intensity'] = df['daily_social_media_hours'] / df['sleep_hours']
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184

In [5]:
df['stress_per_hour'] = df['stress_level'] / df['daily_social_media_hours']
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568,0.253165
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500,4.210526
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053,1.538462
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464,0.135135
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184,0.638298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,1.030303,0.441176
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0,0.287500,3.043478
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0,0.195402,0.588235
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0,0.458824,1.794872
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,0.723077,1.063830

In [6]:
df['anxiety_sleep_ratio'] = df['anxiety_level'] / df['sleep_hours']

In [8]:
df['usage_category'] = pd.cut(
    df['daily_social_media_hours'],
    bins=[0,2,5,10],
    labels=['Low','Medium','High']
)

df['sleep_category'] = pd.cut(
    df['sleep_hours'],
    bins=[0,5,7,10],
    labels=['Poor','Average','Good']
)

In [9]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour,anxiety_sleep_ratio,usage_category,sleep_category
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,1.067568,0.253165,0.270270,High,Good
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,0.237500,4.210526,0.125000,Low,Good
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,0.171053,1.538462,0.526316,Low,Good
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,1.072464,0.135135,1.014493,High,Average
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,0.959184,0.638298,1.020408,Medium,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,1.030303,0.441176,0.606061,High,Average
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0,0.287500,3.043478,0.500000,Medium,Good
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0,0.195402,0.588235,0.114943,Low,Good
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0,0.458824,1.794872,1.058824,Medium,Good
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,0.723077,1.063830,1.076923,Medium,Average

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   int64
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   int64
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   int64
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  usage_intensity           1200 non-null   float64
 14  stress_per_hour           1200 non-null   float64
 15  anxiety_sleep_ratio       1200 non-null   float64
 16  usage_category            1200 non-null   category
 17  sleep_category            1200 non-null   category
dtypes: category(2), float64(8), int64(8)
memory usage: 152.8 KB

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include=['object', 'category']).columns:
    df[col] = le.fit_transform(df[col])

In [14]:
df.sample(15)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_intensity,stress_per_hour,anxiety_sleep_ratio,usage_category,sleep_category
643,17,0,5.5,1,6.3,0.8,2.59,1.6,0,6,8,7,0,0.873016,1.090909,1.269841,0,0
125,19,1,6.5,0,8.1,2.3,2.21,0.4,0,8,8,6,0,0.802469,1.230769,0.987654,0,1
848,19,1,6.0,0,5.6,1.1,2.43,1.7,2,1,3,3,0,1.071429,0.166667,0.535714,0,0
313,13,0,8.0,1,5.4,2.8,3.10,1.9,0,6,10,10,0,1.481481,0.750000,1.851852,0,0
100,13,1,5.1,0,4.1,1.6,3.32,0.8,2,1,3,8,0,1.243902,0.196078,0.731707,0,2
682,14,1,5.2,1,5.5,1.6,3.08,0.5,2,3,8,1,0,0.945455,0.576923,1.454545,0,0
997,17,0,3.1,2,4.2,0.8,2.28,1.6,2,4,9,6,0,0.738095,1.290323,2.142857,2,2
642,16,0,5.3,0,5.6,2.5,2.73,1.3,2,7,10,4,1,0.946429,1.320755,1.785714,0,0
1010,16,0,6.8,2,7.1,2.9,3.26,0.6,1,6,10,4,0,0.957746,0.882353,1.408451,0,1
1193,13,0,7.2,1,8.1,2.1,2.52,0.4,2,3,3,7,0,0.888889,0.416667,0.370370,0,1
491,18,0,5.7,2,6.2,0.5,3.98,1.7,2,7,6,3,0,0.919355,1.228070,0.967742,0,0
1002,15,0,5.0,2,6.3,1.5,2.67,1.1,0,6,2,5,0,0.793651,1.200000,0.317460,2,0
152,13,0,3.9,1,5.0,0.7,2.98,0.3,2,10,8,3,0,0.780000,2.564103,1.600000,2,2
1078,15,0,6.4,0,7.7,0.7,3.86,1.5,0,10,2,7,0,0.831169,1.562500,0.259740,0,1
95,15,0,1.8,1,6.4,2.4,2.16,1.9,2,3,6,9,0,0.281250,1.666667,0.937500,1,0

In [15]:
df =df.astype('float')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   float64
 1   gender                    1200 non-null   float64
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   float64
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   float64
 9   stress_level              1200 non-null   float64
 10  anxiety_level             1200 non-null   float64
 11  addiction_level           1200 non-null   float64
 12  depression_label          1200 non-null   float64
 13  usage_intensity           1200 non-null   float64
 14  stress_per_hour           1200 non-null   float64
 15  anxiety_sleep_ratio       1200 non-null   float64
 16  usage_category            1200 non-null   float64
 17  sleep_category            1200 non-null   float64
dtypes: float64(18)
memory usage: 168.9 KB

In [17]:
df.to_csv('../data/processed/process_Teen_mental_health.csv', index=False)